name: autofix.ci

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 26.9.0
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            docs/pnpm-lock.yaml

      - run: pnpm install

      - run: pnpm --dir docs install

      - name: Fix lint issues
        run: pnpm run lint:fix

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
        with:
          commit-message: "chore: apply automated updates"
