name: PR Lint

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: read
  statuses: write

jobs:
  lint:
    uses: oritwoen/.github/.github/workflows/pr-lint.yml@main
